name: Trigger auto deployment for lab2app

env:
  actionlint_tag: 1.6.23

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/lab2app-AutoDeployTrigger-f4b922c3-5ccc-4278-9acf-c96bb36186d8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Setup actionlint
        run: |
          wget https://github.com/rhysd/actionlint/releases/download/v$(env.actionlint_tag)/actionlint_$(env.actionlint_tag)_linux_amd64.tar.gz
          tar xf actionlint_$(env.actionlint_tag)_linux_amd64.tar.gz -C /usr/local/bin

      - name: Check github actions
        run: actionlint


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: labacr202303.azurecr.io
          username: ${{ secrets.LAB2APP_REGISTRY_USERNAME }}
          password: ${{ secrets.LAB2APP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: labacr202303.azurecr.io/lab2app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LAB2APP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n lab2app -g lab2 --server labacr202303.azurecr.io --username  ${{ secrets.LAB2APP_REGISTRY_USERNAME }} --password ${{ secrets.LAB2APP_REGISTRY_PASSWORD }}
            az containerapp update -n lab2app -g lab2 --image labacr202303.azurecr.io/lab2app:${{ github.sha }}
